<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/hdr2/rosdep/package.xsd" schematypens="application/xml"?>
<package format="3">
  <name>bt_watcher</name>
  <version>0.1.0</version>
  <description>Bluetooth watcher with MQTT communication</description>
  <maintainer email="sherlock@example.com">sherlock</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>python3-aiomqtt</depend>
  <depend>python3-bleak</depend>
  <depend>python3-crcmod</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
